package com.liucw.resumeGenerator.entity;

public class Edu {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column kkb_edu.id
     *
     * @mbg.generated Fri Mar 12 22:46:12 CST 2021
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column kkb_edu.userid
     *
     * @mbg.generated Fri Mar 12 22:46:12 CST 2021
     */
    private Integer userid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column kkb_edu.start
     *
     * @mbg.generated Fri Mar 12 22:46:12 CST 2021
     */
    private String start;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column kkb_edu.end
     *
     * @mbg.generated Fri Mar 12 22:46:12 CST 2021
     */
    private String end;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column kkb_edu.school
     *
     * @mbg.generated Fri Mar 12 22:46:12 CST 2021
     */
    private String school;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column kkb_edu.study
     *
     * @mbg.generated Fri Mar 12 22:46:12 CST 2021
     */
    private String study;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column kkb_edu.description
     *
     * @mbg.generated Fri Mar 12 22:46:12 CST 2021
     */
    private String description;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column kkb_edu.id
     *
     * @return the value of kkb_edu.id
     *
     * @mbg.generated Fri Mar 12 22:46:12 CST 2021
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column kkb_edu.id
     *
     * @param id the value for kkb_edu.id
     *
     * @mbg.generated Fri Mar 12 22:46:12 CST 2021
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column kkb_edu.userid
     *
     * @return the value of kkb_edu.userid
     *
     * @mbg.generated Fri Mar 12 22:46:12 CST 2021
     */
    public Integer getUserid() {
        return userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column kkb_edu.userid
     *
     * @param userid the value for kkb_edu.userid
     *
     * @mbg.generated Fri Mar 12 22:46:12 CST 2021
     */
    public void setUserid(Integer userid) {
        this.userid = userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column kkb_edu.start
     *
     * @return the value of kkb_edu.start
     *
     * @mbg.generated Fri Mar 12 22:46:12 CST 2021
     */
    public String getStart() {
        return start;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column kkb_edu.start
     *
     * @param start the value for kkb_edu.start
     *
     * @mbg.generated Fri Mar 12 22:46:12 CST 2021
     */
    public void setStart(String start) {
        this.start = start == null ? null : start.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column kkb_edu.end
     *
     * @return the value of kkb_edu.end
     *
     * @mbg.generated Fri Mar 12 22:46:12 CST 2021
     */
    public String getEnd() {
        return end;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column kkb_edu.end
     *
     * @param end the value for kkb_edu.end
     *
     * @mbg.generated Fri Mar 12 22:46:12 CST 2021
     */
    public void setEnd(String end) {
        this.end = end == null ? null : end.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column kkb_edu.school
     *
     * @return the value of kkb_edu.school
     *
     * @mbg.generated Fri Mar 12 22:46:12 CST 2021
     */
    public String getSchool() {
        return school;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column kkb_edu.school
     *
     * @param school the value for kkb_edu.school
     *
     * @mbg.generated Fri Mar 12 22:46:12 CST 2021
     */
    public void setSchool(String school) {
        this.school = school == null ? null : school.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column kkb_edu.study
     *
     * @return the value of kkb_edu.study
     *
     * @mbg.generated Fri Mar 12 22:46:12 CST 2021
     */
    public String getStudy() {
        return study;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column kkb_edu.study
     *
     * @param study the value for kkb_edu.study
     *
     * @mbg.generated Fri Mar 12 22:46:12 CST 2021
     */
    public void setStudy(String study) {
        this.study = study == null ? null : study.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column kkb_edu.description
     *
     * @return the value of kkb_edu.description
     *
     * @mbg.generated Fri Mar 12 22:46:12 CST 2021
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column kkb_edu.description
     *
     * @param description the value for kkb_edu.description
     *
     * @mbg.generated Fri Mar 12 22:46:12 CST 2021
     */
    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
    }

    @Override
    public String toString() {
        return "Edu{" +
                "id=" + id +
                ", userid=" + userid +
                ", start='" + start + '\'' +
                ", end='" + end + '\'' +
                ", school='" + school + '\'' +
                ", study='" + study + '\'' +
                ", description='" + description + '\'' +
                '}';
    }

    public Edu(){};

    public Edu(Integer id, Integer userid, String start, String end, String school, String study, String description) {
        this.id = id;
        this.userid = userid;
        this.start = start;
        this.end = end;
        this.school = school;
        this.study = study;
        this.description = description;
    }
}