package com.liucw.resumeGenerator.entity;

public class Skill {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column kkb_skill.id
     *
     * @mbg.generated Fri Mar 12 22:46:12 CST 2021
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column kkb_skill.userid
     *
     * @mbg.generated Fri Mar 12 22:46:12 CST 2021
     */
    private Integer userid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column kkb_skill.keywords
     *
     * @mbg.generated Fri Mar 12 22:46:12 CST 2021
     */
    private String keywords;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column kkb_skill.id
     *
     * @return the value of kkb_skill.id
     *
     * @mbg.generated Fri Mar 12 22:46:12 CST 2021
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column kkb_skill.id
     *
     * @param id the value for kkb_skill.id
     *
     * @mbg.generated Fri Mar 12 22:46:12 CST 2021
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column kkb_skill.userid
     *
     * @return the value of kkb_skill.userid
     *
     * @mbg.generated Fri Mar 12 22:46:12 CST 2021
     */
    public Integer getUserid() {
        return userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column kkb_skill.userid
     *
     * @param userid the value for kkb_skill.userid
     *
     * @mbg.generated Fri Mar 12 22:46:12 CST 2021
     */
    public void setUserid(Integer userid) {
        this.userid = userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column kkb_skill.keywords
     *
     * @return the value of kkb_skill.keywords
     *
     * @mbg.generated Fri Mar 12 22:46:12 CST 2021
     */
    public String getKeywords() {
        return keywords;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column kkb_skill.keywords
     *
     * @param keywords the value for kkb_skill.keywords
     *
     * @mbg.generated Fri Mar 12 22:46:12 CST 2021
     */
    public void setKeywords(String keywords) {
        this.keywords = keywords == null ? null : keywords.trim();
    }

    @Override
    public String toString() {
        return "Skill{" +
                "id=" + id +
                ", userid=" + userid +
                ", keywords='" + keywords + '\'' +
                '}';
    }

    public Skill(){}

    public Skill(Integer id, Integer userid, String keywords) {
        this.id = id;
        this.userid = userid;
        this.keywords = keywords;
    }
}