package com.liucw.resumeGenerator.entity;

public class User {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column kkb_user.id
     *
     * @mbg.generated Fri Mar 12 22:46:12 CST 2021
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column kkb_user.name
     *
     * @mbg.generated Fri Mar 12 22:46:12 CST 2021
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column kkb_user.age
     *
     * @mbg.generated Fri Mar 12 22:46:12 CST 2021
     */
    private Integer age;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column kkb_user.city
     *
     * @mbg.generated Fri Mar 12 22:46:12 CST 2021
     */
    private String city;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column kkb_user.email
     *
     * @mbg.generated Fri Mar 12 22:46:12 CST 2021
     */
    private String email;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column kkb_user.phone
     *
     * @mbg.generated Fri Mar 12 22:46:12 CST 2021
     */
    private String phone;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column kkb_user.weixin
     *
     * @mbg.generated Fri Mar 12 22:46:12 CST 2021
     */
    private String weixin;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column kkb_user.qq
     *
     * @mbg.generated Fri Mar 12 22:46:12 CST 2021
     */
    private String qq;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column kkb_user.weibo
     *
     * @mbg.generated Fri Mar 12 22:46:12 CST 2021
     */
    private String weibo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column kkb_user.sex
     *
     * @mbg.generated Fri Mar 12 22:46:12 CST 2021
     */
    private String sex;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column kkb_user.description
     *
     * @mbg.generated Fri Mar 12 22:46:12 CST 2021
     */
    private String description;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column kkb_user.id
     *
     * @return the value of kkb_user.id
     *
     * @mbg.generated Fri Mar 12 22:46:12 CST 2021
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column kkb_user.id
     *
     * @param id the value for kkb_user.id
     *
     * @mbg.generated Fri Mar 12 22:46:12 CST 2021
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column kkb_user.name
     *
     * @return the value of kkb_user.name
     *
     * @mbg.generated Fri Mar 12 22:46:12 CST 2021
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column kkb_user.name
     *
     * @param name the value for kkb_user.name
     *
     * @mbg.generated Fri Mar 12 22:46:12 CST 2021
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column kkb_user.age
     *
     * @return the value of kkb_user.age
     *
     * @mbg.generated Fri Mar 12 22:46:12 CST 2021
     */
    public Integer getAge() {
        return age;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column kkb_user.age
     *
     * @param age the value for kkb_user.age
     *
     * @mbg.generated Fri Mar 12 22:46:12 CST 2021
     */
    public void setAge(Integer age) {
        this.age = age;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column kkb_user.city
     *
     * @return the value of kkb_user.city
     *
     * @mbg.generated Fri Mar 12 22:46:12 CST 2021
     */
    public String getCity() {
        return city;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column kkb_user.city
     *
     * @param city the value for kkb_user.city
     *
     * @mbg.generated Fri Mar 12 22:46:12 CST 2021
     */
    public void setCity(String city) {
        this.city = city == null ? null : city.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column kkb_user.email
     *
     * @return the value of kkb_user.email
     *
     * @mbg.generated Fri Mar 12 22:46:12 CST 2021
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column kkb_user.email
     *
     * @param email the value for kkb_user.email
     *
     * @mbg.generated Fri Mar 12 22:46:12 CST 2021
     */
    public void setEmail(String email) {
        this.email = email == null ? null : email.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column kkb_user.phone
     *
     * @return the value of kkb_user.phone
     *
     * @mbg.generated Fri Mar 12 22:46:12 CST 2021
     */
    public String getPhone() {
        return phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column kkb_user.phone
     *
     * @param phone the value for kkb_user.phone
     *
     * @mbg.generated Fri Mar 12 22:46:12 CST 2021
     */
    public void setPhone(String phone) {
        this.phone = phone == null ? null : phone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column kkb_user.weixin
     *
     * @return the value of kkb_user.weixin
     *
     * @mbg.generated Fri Mar 12 22:46:12 CST 2021
     */
    public String getWeixin() {
        return weixin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column kkb_user.weixin
     *
     * @param weixin the value for kkb_user.weixin
     *
     * @mbg.generated Fri Mar 12 22:46:12 CST 2021
     */
    public void setWeixin(String weixin) {
        this.weixin = weixin == null ? null : weixin.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column kkb_user.qq
     *
     * @return the value of kkb_user.qq
     *
     * @mbg.generated Fri Mar 12 22:46:12 CST 2021
     */
    public String getQq() {
        return qq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column kkb_user.qq
     *
     * @param qq the value for kkb_user.qq
     *
     * @mbg.generated Fri Mar 12 22:46:12 CST 2021
     */
    public void setQq(String qq) {
        this.qq = qq == null ? null : qq.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column kkb_user.weibo
     *
     * @return the value of kkb_user.weibo
     *
     * @mbg.generated Fri Mar 12 22:46:12 CST 2021
     */
    public String getWeibo() {
        return weibo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column kkb_user.weibo
     *
     * @param weibo the value for kkb_user.weibo
     *
     * @mbg.generated Fri Mar 12 22:46:12 CST 2021
     */
    public void setWeibo(String weibo) {
        this.weibo = weibo == null ? null : weibo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column kkb_user.sex
     *
     * @return the value of kkb_user.sex
     *
     * @mbg.generated Fri Mar 12 22:46:12 CST 2021
     */
    public String getSex() {
        return sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column kkb_user.sex
     *
     * @param sex the value for kkb_user.sex
     *
     * @mbg.generated Fri Mar 12 22:46:12 CST 2021
     */
    public void setSex(String sex) {
        this.sex = sex == null ? null : sex.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column kkb_user.description
     *
     * @return the value of kkb_user.description
     *
     * @mbg.generated Fri Mar 12 22:46:12 CST 2021
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column kkb_user.description
     *
     * @param description the value for kkb_user.description
     *
     * @mbg.generated Fri Mar 12 22:46:12 CST 2021
     */
    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
    }

    @Override
    public String toString() {
        return "User{" +
                "id=" + id +
                ", name='" + name + '\'' +
                ", age=" + age +
                ", city='" + city + '\'' +
                ", email='" + email + '\'' +
                ", phone='" + phone + '\'' +
                ", weixin='" + weixin + '\'' +
                ", qq='" + qq + '\'' +
                ", weibo='" + weibo + '\'' +
                ", sex='" + sex + '\'' +
                ", description='" + description + '\'' +
                '}';
    }

    public User(){};

    public User(Integer id, String name, Integer age, String city, String email, String phone, String weixin, String qq, String weibo, String sex, String description) {
        this.id = id;
        this.name = name;
        this.age = age;
        this.city = city;
        this.email = email;
        this.phone = phone;
        this.weixin = weixin;
        this.qq = qq;
        this.weibo = weibo;
        this.sex = sex;
        this.description = description;
    }
}