package com.liucw.resumeGenerator.entity;

public class Work {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column kkb_work.id
     *
     * @mbg.generated Fri Mar 12 22:46:12 CST 2021
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column kkb_work.userid
     *
     * @mbg.generated Fri Mar 12 22:46:12 CST 2021
     */
    private Integer userid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column kkb_work.start
     *
     * @mbg.generated Fri Mar 12 22:46:12 CST 2021
     */
    private String start;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column kkb_work.end
     *
     * @mbg.generated Fri Mar 12 22:46:12 CST 2021
     */
    private String end;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column kkb_work.company
     *
     * @mbg.generated Fri Mar 12 22:46:12 CST 2021
     */
    private String company;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column kkb_work.job
     *
     * @mbg.generated Fri Mar 12 22:46:12 CST 2021
     */
    private String job;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column kkb_work.description
     *
     * @mbg.generated Fri Mar 12 22:46:12 CST 2021
     */
    private String description;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column kkb_work.id
     *
     * @return the value of kkb_work.id
     *
     * @mbg.generated Fri Mar 12 22:46:12 CST 2021
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column kkb_work.id
     *
     * @param id the value for kkb_work.id
     *
     * @mbg.generated Fri Mar 12 22:46:12 CST 2021
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column kkb_work.userid
     *
     * @return the value of kkb_work.userid
     *
     * @mbg.generated Fri Mar 12 22:46:12 CST 2021
     */
    public Integer getUserid() {
        return userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column kkb_work.userid
     *
     * @param userid the value for kkb_work.userid
     *
     * @mbg.generated Fri Mar 12 22:46:12 CST 2021
     */
    public void setUserid(Integer userid) {
        this.userid = userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column kkb_work.start
     *
     * @return the value of kkb_work.start
     *
     * @mbg.generated Fri Mar 12 22:46:12 CST 2021
     */
    public String getStart() {
        return start;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column kkb_work.start
     *
     * @param start the value for kkb_work.start
     *
     * @mbg.generated Fri Mar 12 22:46:12 CST 2021
     */
    public void setStart(String start) {
        this.start = start == null ? null : start.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column kkb_work.end
     *
     * @return the value of kkb_work.end
     *
     * @mbg.generated Fri Mar 12 22:46:12 CST 2021
     */
    public String getEnd() {
        return end;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column kkb_work.end
     *
     * @param end the value for kkb_work.end
     *
     * @mbg.generated Fri Mar 12 22:46:12 CST 2021
     */
    public void setEnd(String end) {
        this.end = end == null ? null : end.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column kkb_work.company
     *
     * @return the value of kkb_work.company
     *
     * @mbg.generated Fri Mar 12 22:46:12 CST 2021
     */
    public String getCompany() {
        return company;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column kkb_work.company
     *
     * @param company the value for kkb_work.company
     *
     * @mbg.generated Fri Mar 12 22:46:12 CST 2021
     */
    public void setCompany(String company) {
        this.company = company == null ? null : company.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column kkb_work.job
     *
     * @return the value of kkb_work.job
     *
     * @mbg.generated Fri Mar 12 22:46:12 CST 2021
     */
    public String getJob() {
        return job;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column kkb_work.job
     *
     * @param job the value for kkb_work.job
     *
     * @mbg.generated Fri Mar 12 22:46:12 CST 2021
     */
    public void setJob(String job) {
        this.job = job == null ? null : job.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column kkb_work.description
     *
     * @return the value of kkb_work.description
     *
     * @mbg.generated Fri Mar 12 22:46:12 CST 2021
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column kkb_work.description
     *
     * @param description the value for kkb_work.description
     *
     * @mbg.generated Fri Mar 12 22:46:12 CST 2021
     */
    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
    }

    @Override
    public String toString() {
        return "Work{" +
                "id=" + id +
                ", userid=" + userid +
                ", start='" + start + '\'' +
                ", end='" + end + '\'' +
                ", company='" + company + '\'' +
                ", job='" + job + '\'' +
                ", description='" + description + '\'' +
                '}';
    }

    public Work(){};

    public Work(Integer id, Integer userid, String start, String end, String company, String job, String description) {
        this.id = id;
        this.userid = userid;
        this.start = start;
        this.end = end;
        this.company = company;
        this.job = job;
        this.description = description;
    }
}