package com.liucw.resumeGenerator.dao;

import com.liucw.resumeGenerator.entity.Edu;
import org.apache.ibatis.annotations.Mapper;


import java.util.List;

@Mapper
public interface EduMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kkb_edu
     *
     * @mbg.generated Fri Mar 12 22:46:12 CST 2021
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kkb_edu
     *
     * @mbg.generated Fri Mar 12 22:46:12 CST 2021
     */
    int insert(Edu record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kkb_edu
     *
     * @mbg.generated Fri Mar 12 22:46:12 CST 2021
     */
    Edu selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kkb_edu
     *
     * @mbg.generated Fri Mar 12 22:46:12 CST 2021
     */
    List<Edu> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kkb_edu
     *
     * @mbg.generated Fri Mar 12 22:46:12 CST 2021
     */
    int updateByPrimaryKey(Edu record);

    /** 根据userId查到对应教育经历 **/
    List<Edu> selectByUserKey(Integer id);
}