package com.liucw.resumeGenerator.dao;

import com.liucw.resumeGenerator.entity.Skill;
import org.apache.ibatis.annotations.Mapper;


import java.util.List;

@Mapper
public interface SkillMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kkb_skill
     *
     * @mbg.generated Fri Mar 12 22:46:12 CST 2021
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kkb_skill
     *
     * @mbg.generated Fri Mar 12 22:46:12 CST 2021
     */
    int insert(Skill record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kkb_skill
     *
     * @mbg.generated Fri Mar 12 22:46:12 CST 2021
     */
    Skill selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kkb_skill
     *
     * @mbg.generated Fri Mar 12 22:46:12 CST 2021
     */
    List<Skill> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kkb_skill
     *
     * @mbg.generated Fri Mar 12 22:46:12 CST 2021
     */
    int updateByPrimaryKey(Skill record);

    /** 根据userId查对应技能 **/
    Skill selectByUserKey(Integer Id);
}