package com.liucw.resumeGenerator.dao;

import com.liucw.resumeGenerator.entity.User;
import com.liucw.resumeGenerator.entity.Work;
import org.apache.ibatis.annotations.Mapper;

import java.util.List;

@Mapper
public interface UserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kkb_user
     *
     * @mbg.generated Fri Mar 12 22:46:12 CST 2021
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kkb_user
     *
     * @mbg.generated Fri Mar 12 22:46:12 CST 2021
     */
    int insert(User record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kkb_user
     *
     * @mbg.generated Fri Mar 12 22:46:12 CST 2021
     */
    User selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kkb_user
     *
     * @mbg.generated Fri Mar 12 22:46:12 CST 2021
     */
    List<User> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kkb_user
     *
     * @mbg.generated Fri Mar 12 22:46:12 CST 2021
     */
    int updateByPrimaryKey(User record);
}