package com.liucw.resumeGenerator.dao;

import com.liucw.resumeGenerator.entity.Work;
import org.apache.ibatis.annotations.Mapper;

import java.util.List;

@Mapper
public interface WorkMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kkb_work
     *
     * @mbg.generated Fri Mar 12 22:46:12 CST 2021
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kkb_work
     *
     * @mbg.generated Fri Mar 12 22:46:12 CST 2021
     */
    int insert(Work record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kkb_work
     *
     * @mbg.generated Fri Mar 12 22:46:12 CST 2021
     */
    Work selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kkb_work
     *
     * @mbg.generated Fri Mar 12 22:46:12 CST 2021
     */
    List<Work> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table kkb_work
     *
     * @mbg.generated Fri Mar 12 22:46:12 CST 2021
     */
    int updateByPrimaryKey(Work record);


    /** 根据userId查询对应工作经历 **/
    List<Work> selectByUserKey(Integer id);
}